apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "noria-operator.chart" . }}
    component: cluster-role
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["", "core", "extensions", "apps", "noria-operator.io"]
  resources: ["pods", "deployments", "configmaps", "services", "statefulsets", "norias", "norias/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
