apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: norias.{{ .Chart.Name }}.io
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "noria-operator.chart" . }}
    component: cluster-role
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: {{ .Chart.Name }}.io
  versions:
    - name: v1alpha1
      storage: true
      served: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    kind: Noria
    plural: norias
    singular: noria
    shortNames:
    - noria
