apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-service-account
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "noria-operator.chart" . }}
    component: service-account
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
