apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: norias.noria-operator.io
spec:
  group: noria-operator.io
  versions:
    - name: v1alpha1
      storage: true
      served: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    kind: Noria
    plural: norias
    singular: noria
    shortNames:
    - noria
