apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noria-operator
rules:
- apiGroups: ["core", "extensions", "apps", "noria-operator.io"]
  resources: ["deployments", "configmaps", "services", "statefulsets", "norias", "norias/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: noria-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: noria-operator
subjects:
- kind: ServiceAccount
  name: noria-operator
  namespace: nd-spool
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noria-operator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: noria-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      noria-operator.io/kind: "operator"
      noria-operator.io/name: "noria"
  template:
    metadata:
      labels:
        noria-operator.io/kind: "operator"
        noria-operator.io/name: "noria"
    spec:
      serviceAccountName: noria-operator
      containers:
      - env:
        - name: RUST_LOG
          value: debug
        image: fussybeaver/noria-operator:0.4.1
        imagePullPolicy: Always
        name: noria-operator
